### ISSUE TITLE
你好，程序运行报错，请多多指导。

### ISSUE THREAD

**Issue by lsq-hunan** [qingshuiqianhe/testonlie#1]
你好！我的python环境主要：python=3.6，Django==2.1.4，其他基本最近的。但是程序直接运行，报错如下面。是不是我还需要做其他设置？

"C:\Program Files\JetBrains\PyCharm2018.3.2\bin\runnerw64.exe" E:\Python\Python36-32\python.exe C:/Users/Administrator/Desktop/gitTest/testonlie/manage.py runserver 8000
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x072D40C0>
Traceback (most recent call last):
  File "E:\Python\Python36-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "E:\Python\Python36-32\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "E:\Python\Python36-32\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "E:\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "E:\Python\Python36-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "E:\Python\Python36-32\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\Python\Python36-32\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "E:\Python\Python36-32\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "E:\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\gitTest\testonlie\course\models.py", line 25, in <module>
    class Questions(models.Model):
  File "C:\Users\Administrator\Desktop\gitTest\testonlie\course\models.py", line 27, in Questions
    course = models.ForeignKey(Course, verbose_name=u"课程")
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by lsq-hunan** [comment]
在pycharm2018中编辑的

**Comment by lsq-hunan** [comment]
你好，
查了一下是因为指定外键的方式不对，根据提示修改了一下。对数据库内外键定义，需要参数on_delete=models.CASADE。
可能还是我使用Django版本与你的不一样的原因。

**Comment by lsq-hunan** [comment]
由此，能否根据新模块库，修改更新你的项目呢？这样也方便大家学习。
谢谢！

**Comment by flyingsnow0102** [comment]
> 你好！我的python环境主要：python=3.6，Django==2.1.4，其他基本最近的。但是程序直接运行，报错如下面。是不是我还需要做其他设置？
> 
> "C:\Program Files\JetBrains\PyCharm2018.3.2\bin\runnerw64.exe" E:\Python\Python36-32\python.exe C:/Users/Administrator/Desktop/gitTest/testonlie/manage.py runserver 8000
> Unhandled exception in thread started by <function check_errors..wrapper at 0x072D40C0>
> Traceback (most recent call last):
> File "E:\Python\Python36-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
> fn(*args, **kwargs)
> File "E:\Python\Python36-32\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
> autoreload.raise_last_exception()
> File "E:\Python\Python36-32\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
> raise _exception[1] File "E:\Python\Python36-32\lib\site-packages\django\core\management__init__.py", line 337, in execute
> autoreload.check_errors(django.setup)()
> File "E:\Python\Python36-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
> fn(*args, **kwargs)
> File "E:\Python\Python36-32\lib\site-packages\django__init__.py", line 24, in setup
> apps.populate(settings.INSTALLED_APPS)
> File "E:\Python\Python36-32\lib\site-packages\django\apps\registry.py", line 112, in populate
> app_config.import_models()
> File "E:\Python\Python36-32\lib\site-packages\django\apps\config.py", line 198, in import_models
> self.models_module = import_module(models_module_name)
> File "E:\Python\Python36-32\lib\importlib__init__.py", line 126, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 994, in _gcd_import
> File "", line 971, in _find_and_load
> File "", line 955, in _find_and_load_unlocked
> File "", line 665, in _load_unlocked
> File "", line 678, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "C:\Users\Administrator\Desktop\gitTest\testonlie\course\models.py", line 25, in 
> class Questions(models.Model):
> File "C:\Users\Administrator\Desktop\gitTest\testonlie\course\models.py", line 27, in Questions
> course = models.ForeignKey(Course, verbose_name=u"课程")
> TypeError: **init**() missing 1 required positional argument: 'on_delete'

你能运行的了？交流下：QQ491947781

**Comment by lsq-hunan** [comment]
基本步骤如下：
1、在pycharm2018从Github中colone项目到电脑中
2、为项目创建虚拟环境venv
3、根据requirement.txt，pycharm会自动提示批量安装库，其中包括Django==1.11.4，xadmin==0.6.1
4、运行项目，http://127.0.0.1:8000/register/，浏览器显示“注册”页面，新注册
5、打开数据库（sqlite3）文件，直接修改新注册用户权限为超级用户
6、在管理员页面登陆

期间，采用虚拟环境，所以克隆下来的文件都不修改。实际检验可用。

谢谢分享！学习受益良多。

不知后面是否还考虑更新完善：程序结构功能设计进一步完善；与库包的更新保持一致，以及其他方面。

**Comment by qingshuiqianhe** [comment]
对的。项目是基于py2.7 做的。开发使用虚拟环境，requirement.txt将我的所有开发环境都记录了。这个是我的毕业设计，当时库表设计的也不是很完善。前端也是找的模板。目前没有计划去大改，有意向的可以交流修改思路，欢迎提issues。
